import {
  AlarmClock,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Circle,
  Code,
  Coffee,
  Dumbbell,
  Footprints,
  Gamepad2,
  GlassWater,
  GraduationCap,
  Heart,
  House,
  Moon,
  Music,
  PawPrint,
  PenLine,
  Phone,
  Pill,
  Plane,
  Send,
  ShoppingCart,
  ShowerHead,
  SprayCan,
  Sun,
  Target,
  Users,
  UtensilsCrossed,
  Wallet,
} from "lucide-react";

// Keys are persisted on every Task/Habit/Interest row and sent to the AI
// tools — never rename or remove one, only add. The backend keeps a copy of
// this key list in app/services/tools.py (ICON_KEYS); test_icon_keys.py fails
// if the two drift. Insertion order is the icon picker's order.
export const ICONS = {
  alarm: AlarmClock,
  morning: Sun,
  sleep: Moon,
  workout: Dumbbell,
  walk: Footprints,
  bike: Bike,
  shower: ShowerHead,
  meal: UtensilsCrossed,
  coffee: Coffee,
  water: GlassWater,
  meds: Pill,
  health: Heart,
  mind: Brain,
  reading: BookOpen,
  study: GraduationCap,
  writing: PenLine,
  work: Briefcase,
  code: Code,
  call: Phone,
  send: Send,
  target: Target,
  social: Users,
  home: House,
  clean: SprayCan,
  shopping: ShoppingCart,
  money: Wallet,
  travel: Plane,
  music: Music,
  game: Gamepad2,
  pet: PawPrint,
  default: Circle,
} as const;

export type IconKey = keyof typeof ICONS;

// Matched as plain substrings, first entry wins — so order is load-bearing
// (e.g. "study" must precede "call" or "Recall" becomes a phone call), and a
// short keyword that hides inside common words ("cat" in "vacation", "rent"
// in "parent") is left out rather than risk a wrong guess.
const ICON_KEYWORDS: { key: IconKey; keywords: string[] }[] = [
  { key: "pet", keywords: ["dog", "puppy", "kitten", "litter box"] },
  {
    key: "meds",
    keywords: [
      "pill",
      "vitamin",
      "supplement",
      "medicine",
      "medication",
      "meds",
      "tablet",
      "folic",
    ],
  },
  {
    key: "workout",
    keywords: [
      "workout",
      "gym",
      "exercise",
      "lift",
      "weights",
      "training",
      "run",
      "running",
      "jog",
      "push",
      "pull",
      "squat",
      "deadlift",
      "bench",
    ],
  },
  { key: "walk", keywords: ["walk", "steps", "hike", "hiking", "movement", "stroll"] },
  { key: "shower", keywords: ["shower", "bath", "wash", "hygiene", "groom"] },
  {
    key: "meal",
    keywords: [
      "eat",
      "breakfast",
      "lunch",
      "dinner",
      "food",
      "meal",
      "cook",
      "cooking",
      "snack",
      "brunch",
    ],
  },
  { key: "bike", keywords: ["bike", "cycling", "cycle", "bicycle", "ride"] },
  { key: "water", keywords: ["water", "hydrate", "drink"] },
  {
    key: "code",
    keywords: ["code", "coding", "program", "algorithm", "debug", "leetcode", "deploy"],
  },
  {
    key: "study",
    keywords: [
      "study",
      "studying",
      "learn",
      "class",
      "lecture",
      "course",
      "exam",
      "homework",
      "recall",
      "revision",
      "flashcard",
      "research",
    ],
  },
  { key: "reading", keywords: ["read", "reading", "book"] },
  { key: "coffee", keywords: ["coffee", "tea", "cafe", "espresso", "latte"] },
  {
    key: "shopping",
    keywords: ["shop", "grocery", "groceries", "buy", "purchase", "store", "market"],
  },
  { key: "writing", keywords: ["write", "writing", "journal", "diary", "blog", "essay"] },
  {
    key: "send",
    keywords: ["apply", "application", "outreach", "referral", "follow-up", "follow up", "submit"],
  },
  {
    key: "work",
    keywords: [
      "work",
      "meeting",
      "email",
      "office",
      "project",
      "standup",
      "interview",
      "review",
      "presentation",
      "report",
    ],
  },
  { key: "target", keywords: ["goal", "mock", "prep", "practice", "behavioural", "behavioral"] },
  { key: "call", keywords: ["call", "phone", "facetime"] },
  { key: "social", keywords: ["friend", "family", "party", "hangout", "date night", "social"] },
  { key: "mind", keywords: ["meditat", "prayer", "praying", "mindful", "breathe", "breathing"] },
  { key: "sleep", keywords: ["sleep", "bedtime", "wind down"] },
  { key: "morning", keywords: ["morning", "sunrise"] },
  {
    key: "health",
    keywords: [
      "health",
      "doctor",
      "yoga",
      "stretch",
      "therapy",
      "dentist",
      "hospital",
      "checkup",
      "facial",
      "skincare",
    ],
  },
  {
    key: "clean",
    keywords: ["clean", "laundry", "tidy", "vacuum", "dishes", "chores"],
  },
  { key: "home", keywords: ["home", "house", "garden", "repair"] },
  {
    key: "money",
    keywords: ["budget", "bill", "bank", "taxes", "invoice", "finance", "expense"],
  },
  { key: "travel", keywords: ["flight", "travel", "airport", "vacation", "holiday", "road trip"] },
  { key: "music", keywords: ["music", "guitar", "piano", "singing", "concert"] },
  { key: "game", keywords: ["game", "gaming"] },
  { key: "alarm", keywords: ["wake", "alarm", "routine"] },
];

export function guessIcon(title: string): IconKey | null {
  const lower = title.toLowerCase();
  for (const { key, keywords } of ICON_KEYWORDS) {
    if (keywords.some((kw) => lower.includes(kw))) return key;
  }
  return null;
}
